### ISSUE TITLE
Can't create event

### ISSUE THREAD

**Issue by joaocosta-azores** [nathanlesage/oc-campaignr#1]
I'e tried to create first event without success.
Error:

> "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'repeat_mode' at row 1 (SQL: insert into `hendrikerz_campaignr_events` (`name`, `slug`, `time_begin`, `repeat_event`, `time_end`, `repeat_mode`, `end_repeat_on`, `description`, `location_street`, `location_number`, `location_zip`, `location_city`, `location_country`, `location_misc`, `dow`, `dom`, `wom`, `mon`, `year`, `end_day`, `end_mon`, `end_year`, `updated_at`, `created_at`) values (teste, teste, 2019-02-23 02:10:00, 0, 2019-02-24 03:10:00, , , TESTE, , , , , , , 6, 23, 4, 2, 2019, 24, 2, 2019, 2019-02-15 16:00:22, 2019-02-15 16:00:22))" on line 664 of /var/www/october/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by nathanlesage** [comment]
That's strange, I thought I fixed this bug. But I found another, apparently the Schema Builder allows an empty field for repeat_event, which should not happen. I'm investigating …
