### ISSUE TITLE
Using calander on frontend to dispay events in calander format but when click on next and previous months, page reload

### ISSUE THREAD

**Issue by amjadniazi48** [nathanlesage/oc-campaignr#2]
Hi there i m using calander on my home page but when i click previous year or next year function the page reloads and nothing happen

**Comment by nathanlesage** [comment]
Hey,

did you use the default components and also add the parameters as indicated to the URL of the component?

Here's the navigation of the component (so the standard implementation): https://github.com/nathanlesage/oc-campaignr/blob/master/components/calendar/navigation.htm

The URL should look something like ´/my/path/:year?/:month?´. Just tested it, it should work with the current October build!

**Comment by amjadniazi48** [comment]
yes it works now by putting the url in my home page but when i click the previous and next month button the full page reloads again, it should by loaded through ajax , thanks for the reply

**Comment by nathanlesage** [comment]
Surely! If you'd like to implement this, I'm happy to accept your PR.
