### ISSUE TITLE
Event with repeat does not repeat

### ISSUE THREAD

**Issue by Somel1978** [nathanlesage/oc-campaignr#5]
In the Upcoming component.

If an event repeats every day for example, it will only shows on the list on the next upcoming day and not every time it repeats.

Lets say an event repeats today and two more days.
It will show Today the event but tomorrow will not be listed in the upcoming list.
It display correctly in Calendar format.

**Comment by nathanlesage** [comment]
Thanks for notifying me, I'll have a look!

**Comment by nathanlesage** [comment]
Closing in preparation to archiving this repository.
