### ISSUE TITLE
translatable content

### ISSUE THREAD

**Issue by andreasdueren** [nathanlesage/oc-campaignr#6]
Hi! I'm trying to set up multi-language events. But it won't show the language selector in the text fields as it normally does. 
Is this expected behaviour and I need to manually implement that differently or is there a problem with my local installation?
![Screenshot 2021-01-31 at 09 28 05](https://user-images.githubusercontent.com/46187667/106378643-c4a80a00-63a6-11eb-9913-900637d55993.png)
![Screenshot 2021-01-31 at 09 27 48](https://user-images.githubusercontent.com/46187667/106378645-c7a2fa80-63a6-11eb-8f7c-e9e8a54000d1.png)

**Comment by nathanlesage** [comment]
I don't really know. But if you find a way to enable that functionality, feel free to open a PR. I currently don't have time to work on this plugin myself, but I'll merge good PRs.

**Comment by nathanlesage** [comment]
Closing in preparation to archiving this repository.
