### ISSUE TITLE
[IDEA] calender per user/usergroup

### ISSUE THREAD

**Issue by NielsvandenDries** [nathanlesage/oc-campaignr#9]
It would be nice if multiple calendars could be created that could be assigned to users or usergroups

**Comment by nathanlesage** [comment]
That is definitely an interesting idea. However, I no longer maintain this repo (I just forgot to archive it), since OctoberCMS went paywalled. I'll likely port this plugin to WinterCMS some time next year, as I did with my other plugin!

**Comment by NielsvandenDries** [comment]
Hmmm, to bad, I will also have a look at WinterCMS, But for now my boss wants OctoberCMS.
Thx for the reply
